import type { AllIconTypes } from "./icons";

export const ICON_WHITE_BG = {
  bg: true,
  bh: true,
  bl: true,
  cy: true,
  cz: true,
  dz: true,
  ee: true,
  fo: true,
  "gb-eng": true,
  "gb-nir": true,
  "gb-wls": true,
  ge: true,
  gg: true,
  gi: true,
  gl: true,
  id: true,
  je: true,
  jp: true,
  "jp-kyoto-city": true,
  "jp-nara-pref": true,
  "jp-otsu-city": true,
  "jp-wakayama-city": true,
  "jp-wakayama-pref": true,
  kr: true,
  mc: true,
  mt: true,
  pk: true,
  pl: true,
  qa: true,
  rs: true,
  ru: true,
  sg: true,
  si: true,
  sk: true,
  sm: true,
  vi: true,
  yt: true,
} as { [key in keyof typeof AllIconTypes]: boolean };
